=== hkara2/pmsixml/src/main/resources/fr/gpmsi/pmsixml/nx/NX-CCAM-22-03.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="NX">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ENR">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="CHAMP" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="NOM" use="required" fixed="" />
									<xs:attribute name="NOMLONG" use="required" />
									<xs:attribute name="TYPE" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="A" />
												<xs:enumeration value="N" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="LNG" type="xs:integer" use="required" />
									<xs:attribute name="DESCRIPTION" use="required" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="NOM" use="required" />
						<xs:attribute name="NOMLONG" use="required" />
						<xs:attribute name="TYP" type="xs:integer" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== hkara2/pmsixml/src/main/resources/fr/gpmsi/pmsixml/nx/CAM1401.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE NX><!-- Ajouté pour ne pas avoir de warning dans Eclipse. Plus tard je ferait peut être un document .xsd pour spécifier la structure. -->
<!--
Définition de ce qu'il faut lire comme contenu NX d'un fichier CCAM.
Note :
Les éléments peuvent contenir '-' comme séparateur, mais les noms qui sont dans l'attribut NOM utilisent toujour '_' car ils peuvent être transformés en nom de colonne et là le '-' est beaucoup moins pratique. 
-->
		<!-- 
		<CHAMP NOM="" NOMLONG="" TYPE="A" LNG="" DESCRIPTION="" />
		-->
<NX><!-- xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="NX-CCAM-22-03.xsd" -->
	<ENR TYP="000" NOM="DEBUT" NOMLONG="Début de fichier">
		<CHAMP NOM="TYPE_EMETTEUR" NOMLONG="Type d’émetteur" TYPE="A" LNG="2" DESCRIPTION="Non contrôlé" />		
		<CHAMP NOM="NUMERO_EMETTEUR" NOMLONG="Numéro d’émetteur" TYPE="N" LNG="14" DESCRIPTION="Valeur ‘0000000100000’" />
		<CHAMP NOM="PROGRAMME_EMETTEUR" NOMLONG="Programme émetteur" TYPE="A" LNG="6" DESCRIPTION="Valeur ‘CODCAM’" />
		<CHAMP NOM="TYPE_DESTINATAIRE" NOMLONG="Type de destinataire" TYPE="A" LNG="2" DESCRIPTION="Valeur ‘CT’" />
		<CHAMP NOM="NUMERO_DESTINATAIRE" NOMLONG="Numéro de destinataire" TYPE="A" LNG="14" DESCRIPTION="Valeur ‘00000001000000’" />
		<CHAMP NOM="PROGRAMME_DESTINATAIRE" NOMLONG="Programme destinataire" TYPE="A" LNG="6" DESCRIPTION="Valeur ‘NAX310’" />
		<CHAMP NOM="TYPE_ECHANGE" NOMLONG="Application - type d’échange" TYPE="A" LNG="2" DESCRIPTION="Valeur ‘NA’" />
		<CHAMP NOM="IDENTIFICATION_FICHIER" NOMLONG="Identification du fichier" TYPE="A" LNG="3" DESCRIPTION="Valeur ‘CAM’" />
		<CHAMP NOM="DATE_CREATION_FICHIER" NOMLONG="Date de création du fichier" TYPE="N" LNG="8" DESCRIPTION="Sous la forme SSAAMMJJ" />
		<CHAMP NOM="INFORMATIONS_NOEMIE" NOMLONG="Informations NOEMIE" TYPE="A" LNG="24" DESCRIPTION="Inutilisé" />
		<CHAMP NOM="NUMERO_CHRONOLOGIQUE" NOMLONG="Numéro chronologie" TYPE="N" LNG="5" DESCRIPTION="Valeur &gt; 00000" />
		<CHAMP NOM="TYPE_FICHIER" NOMLONG="Type de fichier" TYPE="N" LNG="1" DESCRIPTION="Valeur ‘0’ = mise à jour, ‘1’ = fichier en annule et remplace" />
		<CHAMP NOM="NUMERO_VERSION" NOMLONG="Numéro de version" TYPE="N" LNG="4" DESCRIPTION="Valeur '1401' Format AAVV (AA = Année, VV = N° dans l’année) Version de structure de Base" />
	</ENR>
	
	<!-- Pour copier/coller (debut) ++>
	<ENR TYP="" RUB="01" SEQ="01" NOM="" NOMLONG="">
	  <DESCRIPTION>
	  </DESCRIPTION>
	  <CHAMP NOM="" NOMLONG="" TYPE="" LNG="" DESCRIPTION="" />
	</ENR>
	<!++ Pour copier/coller (fin) -->
	
	<ENR TYP="001" RUB="01" SEQMIN="01" SEQMAX="99" NOM="TB01" NOMLONG="table TB01 - 'Modes de traitement impliquant un taux d'hospitalisation'">
	  <DESCRIPTION>
 		    Cet enregistrement, qui est facultatif, regroupe toutes les informations contenues dans la
			table TB01 – "Modes de traitement impliquant un taux d'hospitalisation".\n
			En fonction du nombre d'occurrences d'éléments composant la table, la "Séquence" peut
			évoluer de 01 à 99.
			Le nombre maximum d'enregistrements de type 001 est de 99.
			Il est donc possible d’associer jusqu’à 6 * 99 = 594 occurrences d’éléments pour la table
			TB01.
			Les occurrences sont triées par mode de traitement croissant puis date début
			décroissante.
	  </DESCRIPTION>
	  <SOUS-ENR MIN="1" MAX="6" NOM="ENR_TB01" NOMLONG="Enregistrements TB01">
	    <CHAMP NOM="MODE_TRAIT" NOMLONG="Mode de traitement" TYPE="N" LNG="2" DESCRIPTION="" />
	    <CHAMP NOM="DATE_DEBUT" NOMLONG="Date de début" TYPE="D" LNG="8" DESCRIPTION="" />
	    <CHAMP NOM="DATE_FIN" NOMLONG="Date de fin" TYPE="D" LNG="8" DESCRIPTION="" />
	  </SOUS-ENR>
	</ENR>

	<ENR TYP="002" RUBMIN="01" RUBMAX="99" SEQMIN="01" SEQMAX="99" NOM="TB02" NOMLONG="TB02 – Association 'Code association non prévue' &amp; 'Coefficient'">
	  <DESCRIPTION>
		  Cet enregistrement, qui est obligatoire pour un fichier total, regroupe toutes les
		  informations contenues dans la table TB02 – Association «Code association non prévue»
		  &amp; «Coefficient».
		  En fonction du nombre d'occurrences d'éléments composant la table, la "Rubrique" peut
		  évoluer de 01 à 99 et, pour chaque valeur de la "Rubrique", la "Séquence" peut évoluer
		  de 01 à 99.
		  Le nombre maximum d'enregistrements de type 002 est de 99 * 99 = 9801.
		  Il est donc possible d’associer jusqu’à 5 * 99 * 99 = 49005 occurrences d’éléments pour
		  la table TB02.
		  Les occurrences sont triées par "GRILLE TARIFAIRE" croissant, puis "code association"
		  croissant, puis "date début" décroissante.
	  </DESCRIPTION>
	  <SOUS-ENR MIN="1" MAX="5" NOM="ENR-TB02" NOMLONG="Enregistrements TB02">
		<CHAMP NOM="GRILLE_TARIF" NOMLONG="Grille tarifaire" TYPE="N" LNG="3" DESCRIPTION="Code de Grille Tarifaire à laquelle sont rattachés les champs suivants : Code association, Date début, Date fin, Coefficient" />
		<CHAMP NOM="CODE_ASSOC" NOMLONG="Code association" TYPE="A" LNG="1" DESCRIPTION="" />
		<CHAMP NOM="DATE_DEBUT" NOMLONG="Date début" TYPE="D" LNG="8" DESCRIPTION="" />
		<CHAMP NOM="DATE_FIN" NOMLONG="Date fin" TYPE="D" LNG="8" DESCRIPTION="" />
		<CHAMP NOM="COEFF" NOMLONG="Coefficient" TYPE="N" LNG="4" ECH="1" DESCRIPTION="" />
	  </SOUS-ENR>
	</ENR>
	
	<ENR TYP="003" RUBMIN="01" RUBMAX="99" SEQMIN="01" SEQMAX="99" NOM="TB03" NOMLONG="TB03 – Règle tarifaire &amp; Coefficient'">
	  <DESCRIPTION>
		Cet enregistrement, qui est obligatoire pour un fichier total, regroupe toutes les
		informations contenues dans la table TB03 – «Règle tarifaire» &amp; «Coefficient».
		En fonction du nombre d'occurrences d'éléments composant la table, la "Rubrique" peut
		évoluer de 01 à 99 et, pour chaque valeur de la "Rubrique", la "Séquence" peut évoluer
		de 01 à 99.
		Le nombre maximum d'enregistrements de type 003 est de 99 * 99 = 9801.
		Il est donc possible d’associer jusqu’à 5 * 99 * 99 = 49005 occurrences d’éléments pour
		la table TB03.
		Les occurrences sont triées par "GRILLE TARIFAIRE" croissant, puis "Règle tarifaire"
		croissante, puis "Date début" décroissante.
	  </DESCRIPTION>
	  <SOUS-ENR MIN="1" MAX="5" NOM="ENR-TB03" NOMLONG="Enregistrements TB03">
		<CHAMP NOM="GRILLE_TARIF" NOMLONG="Grille tarifaire" TYPE="N" LNG="3" DESCRIPTION="Code de Grille Tarifaire à laquelle sont rattachés les champs suivants : Règle tarifaire, Date début, Date fin, Coefficient" />
		<CHAMP NOM="REGLE_TARIF" NOMLONG="Règle tarifaire" TYPE="A" LNG="1" DESCRIPTION="" />
		<CHAMP NOM="DATE_DEBUT" NOMLONG="Date début" TYPE="D" LNG="8" DESCRIPTION="" />
		<CHAMP NOM="DATE_FIN" NOMLONG="Date fin" TYPE="D" LNG="8" DESCRIPTION="" />
		<CHAMP NOM="COEFF" NOMLONG="Coefficient" TYPE="N" LNG="4" ECH="1" DESCRIPTION="" />
	  </SOUS-ENR>
	</ENR>
	
	<ENR TYP="004" RUB="01" SEQMIN="01" SEQMAX="99" NOM="TB04" NOMLONG="TB04">
	  <DESCRIPTION>
		Cet enregistrement, qui est obligatoire pour un fichier total, regroupe toutes les
		informations contenues dans la table TB04 – Regroupement de spécialités.
		En fonction du nombre d'occurrences d'éléments composant la table, la "Séquence" peut
		évoluer de 01 à 99.
		Le nombre maximum d'enregistrements de type 004 est de 99.
		Il est donc possible d’associer jusqu’à 6 * 99 = 594 occurrences d’éléments pour la table
		TB04.
		Les occurrences sont triées par "Spécialité" croissante puis "Date début" décroissante.
	  </DESCRIPTION>
	  <SOUS-ENR MIN="1" MAX="6" NOM="ENR-TB04" NOMLONG="Enregistrement TB04">
		<CHAMP NOM="SPECIALITE" NOMLONG="Spécialité" TYPE="N" LNG="2" DESCRIPTION="" />
		<CHAMP NOM="DATE_DEBUT" NOMLONG="Date début" TYPE="D" LNG="8" DESCRIPTION="" />
		<CHAMP NOM="DATE_FIN" NOMLONG="Date fin" TYPE="D" LNG="8" DESCRIPTION="" />
		<CHAMP NOM="CLASSE_SPE" NOMLONG="Classe de spécialité" TYPE="A" LNG="2" DESCRIPTION="" />
	  </SOUS-ENR>
	</ENR>
	
	<ENR TYP="005" RUB="01" SEQMIN="01" SEQMAX="99" NOM="TB05" NOMLONG="TB05 - 'Code nature de prestation' &amp; 'Type de forfait'">
	  <DESCRIPTION>
		Cet enregistrement, qui est obligatoire pour un fichier total, regroupe toutes les
		informations contenues dans la table TB05 – Association «Code nature de prestation» &amp;
		«Type de forfait».
		En fonction du nombre d'occurrences d'éléments composant la table, la "Séquence" peut
		évoluer de 01 à 99.
		Le nombre maximum d'enregistrements de type 005 est de 99.
		Il est donc possible d’associer jusqu’à 6 * 99 = 594 occurrences d’éléments pour la table
		TB05.
		Les occurrences sont triées par "Nature de prestation" croissante puis "Date de début"
		décroissante.		  
	  </DESCRIPTION>
	  <SOUS-ENR MIN="1" MAX="6" NOM="ENR-TB05" NOMLONG="Enregistrement TB05">
		<CHAMP NOM="NAT_PRESTF_CCAM" NOMLONG="Nature de prestation de type forfait CCAM" TYPE="A" LNG="3" DESCRIPTION="" />
		<CHAMP NOM="DATE_DEBUT" NOMLONG="Date début" TYPE="D" LNG="8" DESCRIPTION="" />
		<CHAMP NOM="DATE_FIN" NOMLONG="Date fin" TYPE="D" LNG="8" DESCRIPTION="" />
		<CHAMP NOM="TYPE_FORFT" NOMLONG="Type de forfait" TYPE="A" LNG="1" DESCRIPTION="" />
	  </SOUS-ENR>
	</ENR>
	
	<ENR TYP="006" RUB="01" SEQMIN="01" SEQMAX="99" NOM="TB06" NOMLONG="TB06 - Code modificateur &amp; Age du bénéficiaire">
	  <DESCRIPTION>
		Cet enregistrement, qui est facultatif, regroupe toutes les informations contenues dans la
		table TB06 – Comptabilité «Code modificateur» &amp; «Age du bénéficiaire».
		En fonction du nombre d'occurrences d'éléments composant la table, la "Séquence" peut
		évoluer de 01 à 99.
		Le nombre maximum d'enregistrements de type 006 est de 99.
		Il est donc possible d’associer jusqu’à 4 * 99 = 396 occurrences d’éléments pour la table
		TB06.
		Les occurrences sont triées par "Code modificateur" décroissant puis "Date début"
		décroissante.
	  </DESCRIPTION>
	  <SOUS-ENR MIN="1" MAX="4" NOM="ENR-TB06" NOMLONG="Enregistrement TB06">
		<CHAMP NOM="CODE_MODIF" NOMLONG="Code modificateur" TYPE="A" LNG="1" DESCRIPTION="" />
		<CHAMP NOM="DATE_DEBUT" NOMLONG="Date début" TYPE="D" LNG="8" DESCRIPTION="" />
